---
blank_issues_enabled: false
contact_links:
  - name: CoreData Community Support
    url: https://github.com/developer-academy-unina/Tutorial-CoreData/discussions
    about: Please ask and answer questions here.
